import com.sjzsqjy.www.data.blood.BloodUser
import org.codehaus.groovy.grails.plugins.metadata.GrailsPlugin
import org.codehaus.groovy.grails.web.pages.GroovyPage
import org.codehaus.groovy.grails.web.taglib.*
import org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException
import org.springframework.web.util.*
import grails.util.GrailsUtil

class gsp_hospitalNew_bloodUser_form_gsp extends GroovyPage {
public String getGroovyPageFileName() { "/WEB-INF/grails-app/views/bloodUser/_form.gsp" }
public Object run() {
Writer out = getOut()
Writer codecOut = getCodecOut()
registerSitemeshPreprocessMode()
printHtmlPart(0)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'clinic', 'error'))
printHtmlPart(1)
invokeTag('message','g',7,['code':("bloodUser.clinic.label"),'default':("Clinic")],-1)
printHtmlPart(2)
invokeTag('select','g',10,['id':("clinic"),'name':("clinic.id"),'from':(com.sjzsqjy.www.statistics.Clinic.list()),'optionKey':("id"),'value':(bloodUserInstance?.clinic?.id),'class':("many-to-one"),'noSelection':(['null': ''])],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'age', 'error'))
printHtmlPart(4)
invokeTag('message','g',15,['code':("bloodUser.age.label"),'default':("Age")],-1)
printHtmlPart(2)
invokeTag('textField','g',18,['name':("age"),'value':(bloodUserInstance?.age)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'bedNum', 'error'))
printHtmlPart(5)
invokeTag('message','g',23,['code':("bloodUser.bedNum.label"),'default':("Bed Num")],-1)
printHtmlPart(2)
invokeTag('textField','g',26,['name':("bedNum"),'value':(bloodUserInstance?.bedNum)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'checkNum', 'error'))
printHtmlPart(6)
invokeTag('message','g',31,['code':("bloodUser.checkNum.label"),'default':("Check Num")],-1)
printHtmlPart(2)
invokeTag('textField','g',34,['name':("checkNum"),'value':(bloodUserInstance?.checkNum)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'hospitalNum', 'error'))
printHtmlPart(7)
invokeTag('message','g',39,['code':("bloodUser.hospitalNum.label"),'default':("Hospital Num")],-1)
printHtmlPart(2)
invokeTag('textField','g',42,['name':("hospitalNum"),'value':(bloodUserInstance?.hospitalNum)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'keBie', 'error'))
printHtmlPart(8)
invokeTag('message','g',47,['code':("bloodUser.keBie.label"),'default':("Ke Bie")],-1)
printHtmlPart(2)
invokeTag('textField','g',50,['name':("keBie"),'value':(bloodUserInstance?.keBie)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'keyStr', 'error'))
printHtmlPart(9)
invokeTag('message','g',55,['code':("bloodUser.keyStr.label"),'default':("Key Str")],-1)
printHtmlPart(2)
invokeTag('textField','g',58,['name':("keyStr"),'value':(bloodUserInstance?.keyStr)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'name', 'error'))
printHtmlPart(10)
invokeTag('message','g',63,['code':("bloodUser.name.label"),'default':("Name")],-1)
printHtmlPart(2)
invokeTag('textField','g',66,['name':("name"),'value':(bloodUserInstance?.name)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'patientNum', 'error'))
printHtmlPart(11)
invokeTag('message','g',71,['code':("bloodUser.patientNum.label"),'default':("Patient Num")],-1)
printHtmlPart(2)
invokeTag('textField','g',74,['name':("patientNum"),'value':(bloodUserInstance?.patientNum)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'sampleId', 'error'))
printHtmlPart(12)
invokeTag('message','g',79,['code':("bloodUser.sampleId.label"),'default':("Sample Id")],-1)
printHtmlPart(2)
invokeTag('textField','g',82,['name':("sampleId"),'value':(bloodUserInstance?.sampleId)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'sendDate', 'error'))
printHtmlPart(13)
invokeTag('message','g',87,['code':("bloodUser.sendDate.label"),'default':("Send Date")],-1)
printHtmlPart(2)
invokeTag('textField','g',90,['name':("sendDate"),'value':(bloodUserInstance?.sendDate)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'sendDoctor', 'error'))
printHtmlPart(14)
invokeTag('message','g',95,['code':("bloodUser.sendDoctor.label"),'default':("Send Doctor")],-1)
printHtmlPart(2)
invokeTag('textField','g',98,['name':("sendDoctor"),'value':(bloodUserInstance?.sendDoctor)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'sex', 'error'))
printHtmlPart(15)
invokeTag('message','g',103,['code':("bloodUser.sex.label"),'default':("Sex")],-1)
printHtmlPart(2)
invokeTag('textField','g',106,['name':("sex"),'value':(bloodUserInstance?.sex)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'testDate', 'error'))
printHtmlPart(16)
invokeTag('message','g',111,['code':("bloodUser.testDate.label"),'default':("Test Date")],-1)
printHtmlPart(2)
invokeTag('textField','g',114,['name':("testDate"),'value':(bloodUserInstance?.testDate)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'testDoctor', 'error'))
printHtmlPart(17)
invokeTag('message','g',119,['code':("bloodUser.testDoctor.label"),'default':("Test Doctor")],-1)
printHtmlPart(2)
invokeTag('textField','g',122,['name':("testDoctor"),'value':(bloodUserInstance?.testDoctor)],-1)
printHtmlPart(3)
codecOut.print(hasErrors(bean: bloodUserInstance, field: 'type', 'error'))
printHtmlPart(18)
invokeTag('message','g',127,['code':("bloodUser.type.label"),'default':("Type")],-1)
printHtmlPart(2)
invokeTag('textField','g',130,['name':("type"),'value':(bloodUserInstance?.type)],-1)
printHtmlPart(19)
}
public static final Map JSP_TAGS = new HashMap()
protected void init() {
	this.jspTags = JSP_TAGS
}
public static final String CONTENT_TYPE = 'text/html;charset=UTF-8'
public static final long LAST_MODIFIED = 1345131104282L
public static final String DEFAULT_CODEC = null
}
